In [ ]:
#now start second container 'model'

In [4]:
import tensorflow as tf
import os
from tensorflow import keras
from tensorflow.keras import layers


In [5]:
train_dataset_url = "https://storage.googleapis.com/download.tensorflow.org/data/iris_training.csv"

train_dataset_fp = tf.keras.utils.get_file(fname=os.path.basename(train_dataset_url),
                                           origin=train_dataset_url)

print("Local copy of the dataset file: {}".format(train_dataset_fp))


Local copy of the dataset file: /home/jovyan/.keras/datasets/iris_training.csv


In [6]:
# column order in CSV file
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

feature_names = column_names[:-1]
label_name = column_names[-1]

print("Features: {}".format(feature_names))
print("Label: {}".format(label_name))


Features: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
Label: species


In [7]:
batch_size = 32

train_dataset = tf.data.experimental.make_csv_dataset(
    train_dataset_fp,
    batch_size,
    column_names=column_names,
    label_name=label_name,
    num_epochs=1)


In [8]:
train_dataset

<PrefetchDataset shapes: (OrderedDict([(sepal_length, (None,)), (sepal_width, (None,)), (petal_length, (None,)), (petal_width, (None,))]), (None,)), types: (OrderedDict([(sepal_length, tf.float32), (sepal_width, tf.float32), (petal_length, tf.float32), (petal_width, tf.float32)]), tf.int32)>

In [9]:
features, labels = next(iter(train_dataset))

print(features)


OrderedDict([('sepal_length', <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([5. , 4.6, 6.9, 6.8, 6.5, 7.7, 7.2, 5.8, 5. , 5.6, 5.7, 6.7, 6.5,
       6.3, 4.9, 6.2, 5. , 5.7, 7.6, 4.4, 5. , 5.5, 5.1, 7.3, 5. , 6.9,
       4.8, 6.3, 6.2, 6.1, 5.4, 5.1], dtype=float32)>), ('sepal_width', <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([2.3, 3.2, 3.1, 3. , 3. , 3. , 3.2, 2.7, 3.2, 2.7, 2.8, 3.1, 2.8,
       2.7, 3. , 3.4, 3.5, 2.8, 3. , 2.9, 3.4, 3.5, 3.8, 2.9, 3. , 3.1,
       3.1, 3.4, 2.8, 2.6, 3.9, 3.5], dtype=float32)>), ('petal_length', <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([3.3, 1.4, 5.1, 5.5, 5.8, 6.1, 6. , 5.1, 1.2, 4.2, 4.5, 4.4, 4.6,
       4.9, 1.4, 5.4, 1.6, 4.1, 6.6, 1.4, 1.6, 1.3, 1.6, 6.3, 1.6, 4.9,
       1.6, 5.6, 4.8, 5.6, 1.7, 1.4], dtype=float32)>), ('petal_width', <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([1. , 0.2, 2.3, 2.1, 2.2, 2.3, 1.8, 1.9, 0.2, 1.3, 1.3, 1.4, 1.5,
       1.8, 0.2, 2.3, 0.6, 1.3, 2.1, 0.2, 0.4, 0.2, 0.2, 1.8,

In [10]:
def pack_features_vector(features, labels):
  """Pack the features into a single array."""
  features = tf.stack(list(features.values()), axis=1)
  return features, labels


In [11]:
train_dataset = train_dataset.map(pack_features_vector)


In [12]:
features, labels = next(iter(train_dataset))

print(features[:5])


tf.Tensor(
[[6.3 3.3 4.7 1.6]
 [6.7 3.1 4.4 1.4]
 [5.9 3.2 4.8 1.8]
 [5.7 4.4 1.5 0.4]
 [6.6 3.  4.4 1.4]], shape=(5, 4), dtype=float32)


In [13]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


model = tf.keras.Sequential([
  tf.keras.layers.Dense(10, activation=tf.nn.relu, input_shape=(4,)),  # input shape required
  tf.keras.layers.Dense(10, activation=tf.nn.relu),
  tf.keras.layers.Dense(3)
])


In [14]:
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

def loss(model, x, y, training):
  # training=training is needed only if there are layers with different
  # behavior during training versus inference (e.g. Dropout).
  y_ = model(x, training=training)

  return loss_object(y_true=y, y_pred=y_)


l = loss(model, features, labels, training=False)
print("Loss test: {}".format(l))


def grad(model, inputs, targets):
  with tf.GradientTape() as tape:
    loss_value = loss(model, inputs, targets, training=True)
  return loss_value, tape.gradient(loss_value, model.trainable_variables)

Loss test: 1.4445282220840454


In [17]:
model

In [31]:
!pip3 install kfp --upgrade

     |████████████████████████████████| 224 kB 836 kB/s eta 0:00:01
     |████████████████████████████████| 103 kB 703 kB/s eta 0:00:01
     |████████████████████████████████| 1.7 MB 1.6 MB/s eta 0:00:01     |█████████████████████████▍      | 1.4 MB 1.6 MB/s eta 0:00:01
     |████████████████████████████████| 54 kB 756 kB/s eta 0:00:01
     |████████████████████████████████| 52 kB 566 kB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 87 kB 1.2 MB/s eta 0:00:01
     |████████████████████████████████| 75 kB 1.2 MB/s eta 0:00:01
     |████████████████████████████████| 68 kB 1.2 MB/s eta 0:00:01
  Created wheel for kfp: filename=kfp-1.6.3-py3-none-any.whl size=307129 sha256=6d5e47ecea00a1e1c9e7a3c2ff921a3b7a3ff4fdf361fbacbb6cd426526cd2c5
  Stored in directory: /home/jovyan/.cache/pip/wheels/6d/54/ff/9289e68ed44bee6bcba4113e08c83830fdf9daeb4e1fb18b2d


  Created wheel for kfp-server-api: filename=kfp_server_api-1.6.0-py3-none-any.whl size=92525 sha256=f94ee3cedd1733e2e7096074b7c78dbd07f5c52999e37f1b1d4a9cb76a722f75
  Stored in directory: /home/jovyan/.cache/pip/wheels/73/72/bd/804c3bcea41a99dc328a623d003ba9d7d243f2a59a767ef28c
  Created wheel for strip-hints: filename=strip_hints-0.1.9-py2.py3-none-any.whl size=20994 sha256=cabc0293aa76db0545076960e9ab23f63ca765c29f7ea8662ff0b391c7fe6be8
  Stored in directory: /home/jovyan/.cache/pip/wheels/aa/9f/db/bac771c1bd21fd8d743499e2717bce24b68aad2cd00639c579
  Created wheel for docstring-parser: filename=docstring_parser-0.8.1-py3-none-any.whl size=19678 sha256=c430b20609738891a3dc8e40e3f242092b8219fa07123d22e0bf14d67e09c096
  Stored in directory: /home/jovyan/.cache/pip/wheels/7a/06/c4/9b2f0146899e8d1e7748897e42ad5412b6a025513f89cc4a0f
  Created wheel for fire: filename=fire-0.4.0-py2.py3-none-any.whl size=115928 sha256=1065dbcb89c13e637b384ecdc23038f3a90dd90c7de61ec15c693e95bea5577f
  Store

In [1]:
import kfp

In [2]:
from kfp.components import create_component_from_func

In [3]:
%env KF_PIPELINES_ENDPOINT=http://localhost:3000

env: KF_PIPELINES_ENDPOINT=http://localhost:3000


In [5]:
client = kfp.Client(http://localhost:3000)

SyntaxError: invalid syntax (<ipython-input-5-da1efaec5648>, line 1)

In [6]:
from kfp.components import InputPath, InputTextFile, InputBinaryFile, OutputPath, OutputTextFile, OutputBinaryFile
from kfp.components import func_to_container_op

In [7]:
@func_to_container_op
def consume_one_argument(text: str):
    '''Print small text'''
    print(text)

def constant_to_consumer_pipeline():
    '''Pipeline that passes small constant string to to consumer'''
    consume_task = consume_one_argument('Hello world') # Passing constant as argument to consumer

kfp.Client().create_run_from_pipeline_func(constant_to_consumer_pipeline, arguments={})

MaxRetryError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /apis/v1beta1/healthz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbee0dabd60>: Failed to establish a new connection: [Errno 111] Connection refused'))

In [18]:
pwd

'/flask_jupyter'

In [19]:
cd ../

/


In [20]:
ls

bin@   etc/            lib@    libx32@  opt/   run/   sys/  var/
boot/  flask_jupyter/  lib32@  media/   proc/  sbin@  tmp/
dev/   home/           lib64@  mnt/     root/  srv/   usr/


In [21]:
cd ../

/


In [22]:
ls

bin@   etc/            lib@    libx32@  opt/   run/   sys/  var/
boot/  flask_jupyter/  lib32@  media/   proc/  sbin@  tmp/
dev/   home/           lib64@  mnt/     root/  srv/   usr/


In [23]:
cd home

/home


In [24]:
ls

jovyan/


In [25]:
cd jovyan

/home/jovyan


In [26]:
ls

work/


In [27]:
cd work

/home/jovyan/work


In [28]:
ls

In [47]:
predictions = model(features)
predictions[:5]


<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[ 0.44421005, -0.8054398 ,  1.3052256 ],
       [ 1.4932203 , -1.5861349 ,  2.6036456 ],
       [ 1.5385205 , -1.5579052 ,  2.5676577 ],
       [ 1.9798776 , -1.9625888 ,  3.115481  ],
       [ 0.31596172, -0.6506896 ,  1.3310746 ]], dtype=float32)>

In [48]:
tf.nn.softmax(predictions[:5])


<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0.27381006, 0.07847538, 0.6477146 ],
       [0.24499968, 0.01126727, 0.74373305],
       [0.2601551 , 0.01176175, 0.7280832 ],
       [0.24198711, 0.00469462, 0.75331825],
       [0.24154419, 0.09187245, 0.6665834 ]], dtype=float32)>

In [49]:
print("Prediction: {}".format(tf.argmax(predictions, axis=1)))
print("    Labels: {}".format(labels))


Prediction: [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
    Labels: [0 1 1 2 0 2 2 2 1 2 2 0 2 1 2 0 1 1 0 0 2 0 2 0 0 0 2 1 0 2 0 0]


In [ ]:
#now start the third container optimizer

In [16]:
grad(model, inputs, targets)

NameError: name 'inputs' is not defined

In [ ]:
def grad(model, inputs, targets):
  with tf.GradientTape() as tape:
    loss_value = loss(model, inputs, targets, training=True)
  return loss_value, tape.gradient(loss_value, model.trainable_variables)


In [51]:
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)


In [52]:
loss_value, grads = grad(model, features, labels)

print("Step: {}, Initial Loss: {}".format(optimizer.iterations.numpy(),
                                          loss_value.numpy()))

optimizer.apply_gradients(zip(grads, model.trainable_variables))

print("Step: {},         Loss: {}".format(optimizer.iterations.numpy(),
                                          loss(model, features, labels, training=True).numpy()))


Step: 0, Initial Loss: 1.6734590530395508
Step: 1,         Loss: 1.5789241790771484


In [53]:
## Note: Rerunning this cell uses the same model variables

# Keep results for plotting
train_loss_results = []
train_accuracy_results = []

num_epochs = 201

for epoch in range(num_epochs):
  epoch_loss_avg = tf.keras.metrics.Mean()
  epoch_accuracy = tf.keras.metrics.SparseCategoricalAccuracy()

  # Training loop - using batches of 32


  for x, y in train_dataset:
    # Optimize the model
    loss_value, grads = grad(model, x, y)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))

    # Track progress
    epoch_loss_avg.update_state(loss_value)  # Add current batch loss
    # Compare predicted label to actual label
    # training=True is needed only if there are layers with different
    # behavior during training versus inference (e.g. Dropout).
    epoch_accuracy.update_state(y, model(x, training=True))

  # End epoch
  train_loss_results.append(epoch_loss_avg.result())
  train_accuracy_results.append(epoch_accuracy.result())

  if epoch % 50 == 0:
    print("Epoch {:03d}: Loss: {:.3f}, Accuracy: {:.3%}".format(epoch,
                                                                epoch_loss_avg.result(),
                                                                epoch_accuracy.result()))


Epoch 000: Loss: 1.618, Accuracy: 35.000%
Epoch 050: Loss: 0.339, Accuracy: 95.833%
Epoch 100: Loss: 0.173, Accuracy: 96.667%
Epoch 150: Loss: 0.136, Accuracy: 99.167%
Epoch 200: Loss: 0.109, Accuracy: 98.333%


In [54]:
test_url = "https://storage.googleapis.com/download.tensorflow.org/data/iris_test.csv"

test_fp = tf.keras.utils.get_file(fname=os.path.basename(test_url),
                                  origin=test_url)


8192/573 [============================================================================================================================================================================================================================================================================================================================================================================================================================================] - 0s 0us/step


In [55]:
test_dataset = tf.data.experimental.make_csv_dataset(
    test_fp,
    batch_size,
    column_names=column_names,
    label_name='species',
    num_epochs=1,
    shuffle=False)

test_dataset = test_dataset.map(pack_features_vector)


In [56]:
test_accuracy = tf.keras.metrics.Accuracy()

for (x, y) in test_dataset:
  # training=False is needed only if there are layers with different
  # behavior during training versus inference (e.g. Dropout).
  logits = model(x, training=False)
  prediction = tf.argmax(logits, axis=1, output_type=tf.int32)
  test_accuracy(prediction, y)

print("Test set accuracy: {:.3%}".format(test_accuracy.result()))


Test set accuracy: 96.667%


In [57]:
tf.stack([y,prediction],axis=1)


<tf.Tensor: shape=(30, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 2],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [2, 1],
       [1, 1],
       [2, 2],
       [2, 2],
       [0, 0],
       [2, 2],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [2, 2],
       [0, 0],
       [1, 1],
       [2, 2],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [2, 2],
       [1, 1]], dtype=int32)>

In [58]:
predict_dataset = tf.convert_to_tensor([
    [5.1, 3.3, 1.7, 0.5,],
    [5.9, 3.0, 4.2, 1.5,],
    [6.9, 3.1, 5.4, 2.1]
])

# training=False is needed only if there are layers with different
# behavior during training versus inference (e.g. Dropout).
predictions = model(predict_dataset, training=False)

for i, logits in enumerate(predictions):
  class_idx = tf.argmax(logits).numpy()
  p = tf.nn.softmax(logits)[class_idx]
  name = class_names[class_idx]
  print("Example {} prediction: {} ({:4.1f}%)".format(i, name, 100*p))


Example 0 prediction: Iris setosa (97.9%)
Example 1 prediction: Iris versicolor (96.2%)
Example 2 prediction: Iris virginica (70.4%)


In [5]:
import pandas as pd
import os
import matplotlib.pyplot as plt



In [19]:
data = pd.read_csv("iris_training.csv")
data

120    4  setosa  versicolor  virginica
0    6.4  2.8     5.6         2.2          2
1    5.0  2.3     3.3         1.0          1
2    4.9  2.5     4.5         1.7          2
3    4.9  3.1     1.5         0.1          0
4    5.7  3.8     1.7         0.3          0
..   ...  ...     ...         ...        ...
115  5.5  2.6     4.4         1.2          1
116  5.7  3.0     4.2         1.2          1
117  4.4  2.9     1.4         0.2          0
118  4.8  3.0     1.4         0.1          0
119  5.5  2.4     3.7         1.0          1

[120 rows x 5 columns]

In [28]:
df = pd.DataFrame(data)
df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
df

sepal_length  sepal_width  petal_length  petal_width  species
0             6.4          2.8           5.6          2.2        2
1             5.0          2.3           3.3          1.0        1
2             4.9          2.5           4.5          1.7        2
3             4.9          3.1           1.5          0.1        0
4             5.7          3.8           1.7          0.3        0
..            ...          ...           ...          ...      ...
115           5.5          2.6           4.4          1.2        1
116           5.7          3.0           4.2          1.2        1
117           4.4          2.9           1.4          0.2        0
118           4.8          3.0           1.4          0.1        0
119           5.5          2.4           3.7          1.0        1

[120 rows x 5 columns]