In [3]:
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import create_engine
import os
import pandas as pd

app = Flask(__name__)

engine = create_engine('sqlite:///recommender2.db', echo=False)

for f in os.listdir('data/movies/ml-latest-small'):
    if f[-4:] == '.csv':
        data = pd.read_csv(f'data/movies/ml-latest-small/{f}')
        data.to_sql(f[:-4], engine)
        print(f[0:-4])

links
ratings
movies
tags


In [2]:
engine

Engine(sqlite:///recommender2.db)

In [4]:
watched_movie_id_list = ['70286', '109487', '589']


In [5]:
import numpy as np

movie_id_unique = 'SELECT * FROM movies'
all_movies = pd.read_sql(movie_id_unique, engine)

#remove the input movies from all_movies
movies_not_watched = all_movies[~all_movies['movieId'].isin(watched_movie_id_list)]
movies_not_watched['fake_id'] = np.ones(len(movies_not_watched), dtype =int)

#get all_ratings from sqlite
query = 'SELECT "userId", ratings."movieId", movies.title, rating FROM ratings JOIN movies ON ratings."movieId" = movies."movieId";'
all_ratings = pd.read_sql(query, engine)

#remove the watched movies from all_ratings
not_all_ratings = all_ratings[~all_ratings['movieId'].isin(watched_movie_id_list)]

#remove movieId and ratings of the watched movies???
movieindex = not_all_ratings['movieId'].unique().tolist()
dl_movie2movie_encoded = {x: i for i, x in enumerate(movieindex)}
dl_movie_encoded2movie = {i: x for i, x in enumerate(movieindex)}

not_all_ratings["movie"] = not_all_ratings["movieId"].map(dl_movie2movie_encoded)
not_all_ratings["rating"] = not_all_ratings["rating"].values.astype(np.float32)

#map userId from ?? to not_all_ratings ?? what do i do with the users??

not_all_user_ids = not_all_ratings["userId"].unique().tolist()
dl_user2user_encoded = {x: i for i, x in enumerate(not_all_user_ids)}
dl_userencoded2user = {i: x for i, x in enumerate(not_all_user_ids)}

not_all_ratings["user"] = not_all_ratings["userId"].map(dl_user2user_encoded)

min_rating = min(not_all_ratings["rating"])
max_rating = max(not_all_ratings["rating"])
num_users = len(dl_user2user_encoded)
num_movies = len(dl_movie_encoded2movie)
print(
        "Number of users: {}, Number of Movies: {}, Min rating: {}, Max rating: {}".format(
            num_users, num_movies, min_rating, max_rating
        )
    )

#define training data
df = not_all_ratings.sample(frac=1, random_state=42)
x = not_all_ratings[["user", "movie"]].values

    # Normalize the targets between 0 and 1. Makes it easy to train.
y = not_all_ratings["rating"].apply(lambda x: (x - min_rating) / (max_rating - min_rating)).values
    # Assuming training on 90% of the data and validating on 10%.
train_indices = int(0.9 * df.shape[0])
x_train, x_val, y_train, y_val = (
        x[:train_indices],
        x[train_indices:],
        y[:train_indices],
        y[train_indices:],
    )

#inference
user_movie_array = movies_not_watched[['fake_id','index']]
max_movie_index = user_movie_array['index'].max()
that = user_movie_array.to_numpy()

EMBEDDING_SIZE = 50

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

class RecommenderNet(keras.Model):
        def __init__(self, num_users, num_movies, embedding_size, **kwargs):
            super(RecommenderNet, self).__init__(**kwargs)
            self.num_users = num_users
            self.num_movies = num_movies
            self.embedding_size = embedding_size
            self.user_embedding = layers.Embedding(
                num_users,
                embedding_size,
                embeddings_initializer="he_normal",
                embeddings_regularizer=keras.regularizers.l2(1e-6),
            )
            self.user_bias = layers.Embedding(num_users, 1)
            self.movie_embedding = layers.Embedding(
            #change this line from num_movies to max_movie_index+1
                max_movie_index+1,
                embedding_size,
                embeddings_initializer="he_normal",
                embeddings_regularizer=keras.regularizers.l2(1e-6),
            )
            #and this line (input_dim)
            self.movie_bias = layers.Embedding(max_movie_index+1, 1)

        def call(self, inputs):
            user_vector = self.user_embedding(inputs[:, 0])
            user_bias = self.user_bias(inputs[:, 0])
            movie_vector = self.movie_embedding(inputs[:, 1])
            movie_bias = self.movie_bias(inputs[:, 1])
            dot_user_movie = tf.tensordot(user_vector, movie_vector, 2)
            # Add all the components (including bias)
            x = dot_user_movie + user_bias + movie_bias
            # The sigmoid activation forces the rating to between 0 and 1
            return tf.nn.sigmoid(x)


model = RecommenderNet(num_users, num_movies, EMBEDDING_SIZE)
model.compile(
        loss=tf.keras.losses.BinaryCrossentropy(), optimizer=keras.optimizers.Adam(lr=0.001)
    )
ratings = model.predict(that).flatten()

top_ratings_indices = ratings.argsort()[-10:][::-1]
movies_not_watched.loc[movies_not_watched['index'].isin(top_ratings_indices)]

<ipython-input-5-1ab5e0590fe3>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_not_watched['fake_id'] = np.ones(len(movies_not_watched), dtype =int)
<ipython-input-5-1ab5e0590fe3>:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  not_all_ratings["movie"] = not_all_ratings["movieId"].map(dl_movie2movie_encoded)
<ipython-input-5-1ab5e0590fe3>:23: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the 

Number of users: 610, Number of Movies: 9721, Min rating: 0.5, Max rating: 5.0


index  movieId                                   title  \
2818   2818     3766                Missing in Action (1984)   
2820   2820     3768  Braddock: Missing in Action III (1988)   
2821   2821     3769        Thunderbolt and Lightfoot (1974)   
2826   2826     3783                         Croupier (1998)   
2829   2829     3786            But I'm a Cheerleader (1999)   
2832   2832     3789                  Pawnbroker, The (1964)   
2834   2834     3791                        Footloose (1984)   
2841   2841     3799           Pokémon the Movie 2000 (2000)   
2842   2842     3801              Anatomy of a Murder (1959)   
7112   7112    70862                It Might Get Loud (2008)   

                  genres  fake_id  
2818          Action|War        1  
2820          Action|War        1  
2821              Action        1  
2826         Crime|Drama        1  
2829              Comedy        1  
2832               Drama        1  
2834               Drama        1  
2841  Animation|Children        1  
2842       Drama|Mystery        1  
7112         Documentary        1

In [6]:
recom_titles = movies_not_watched.loc[movies_not_watched['index'].isin(top_ratings_indices)]

In [8]:
recom_titles.to_dict()

{'index': {2818: 2818,
  2820: 2820,
  2821: 2821,
  2826: 2826,
  2829: 2829,
  2832: 2832,
  2834: 2834,
  2841: 2841,
  2842: 2842,
  7112: 7112},
 'movieId': {2818: 3766,
  2820: 3768,
  2821: 3769,
  2826: 3783,
  2829: 3786,
  2832: 3789,
  2834: 3791,
  2841: 3799,
  2842: 3801,
  7112: 70862},
 'title': {2818: 'Missing in Action (1984)',
  2820: 'Braddock: Missing in Action III (1988)',
  2821: 'Thunderbolt and Lightfoot (1974)',
  2826: 'Croupier (1998)',
  2829: "But I'm a Cheerleader (1999)",
  2832: 'Pawnbroker, The (1964)',
  2834: 'Footloose (1984)',
  2841: 'Pokémon the Movie 2000 (2000)',
  2842: 'Anatomy of a Murder (1959)',
  7112: 'It Might Get Loud (2008)'},
 'genres': {2818: 'Action|War',
  2820: 'Action|War',
  2821: 'Action',
  2826: 'Crime|Drama',
  2829: 'Comedy',
  2832: 'Drama',
  2834: 'Drama',
  2841: 'Animation|Children',
  2842: 'Drama|Mystery',
  7112: 'Documentary'},
 'fake_id': {2818: 1,
  2820: 1,
  2821: 1,
  2826: 1,
  2829: 1,
  2832: 1,
  2834: 1,

In [7]:
ratings

array([0.47609052, 0.47977495, 0.4648423 , ..., 0.500226  , 0.4845653 ,
       0.5057441 ], dtype=float32)

In [8]:
top_ratings_indices = ratings.argsort()[-10:][::-1]
top_ratings_indices

array([6858, 6875, 6864, 6851, 6865, 1652, 1643, 1633, 1640, 7826])

In [11]:
top_ratings = ratings.argsort()[-10:]
top_ratings
#อยากจะหาว่า ไอ้ index ที่ได้ top rated เนี่ย ratings มันเท่าไหร่

array([7826, 1640, 1633, 1643, 1652, 6865, 6851, 6864, 6875, 6858])

In [19]:
ratings[0:20]

array([0.47609052, 0.47977495, 0.4648423 , 0.48597628, 0.4771965 ,
       0.47681335, 0.4781804 , 0.46901634, 0.4691418 , 0.47572666,
       0.46212783, 0.46428114, 0.46272257, 0.46190292, 0.47395885,
       0.4693534 , 0.4619007 , 0.46194667, 0.47347406, 0.46449518],
      dtype=float32)

In [14]:
ratings[0:20][1:10]

array([0.47977495, 0.4648423 , 0.48597628, 0.4771965 , 0.47681335,
       0.4781804 , 0.46901634, 0.4691418 , 0.47572666], dtype=float32)

In [18]:
ratings[0:20][10:]

array([0.46212783, 0.46428114, 0.46272257, 0.46190292, 0.47395885,
       0.4693534 , 0.4619007 , 0.46194667, 0.47347406, 0.46449518],
      dtype=float32)

In [20]:
ratings[6858]

0.52203035

In [36]:
ratings[6875]

0.49422476

In [34]:
ratings[7826]

0.49750137

In [ ]:
array([6858, 6875, 6864, 6851, 6865, 1652, 1643, 1633, 1640, 7826])

ทำไม ratings[7826] ไม่ใช่ 0.51912624 ตาม ratings[-10:] หลังจากที่ sort แล้ว?? ไม่ใช่ ratings ที่มากที่สุดหรอกเหรอ

In [ ]:
ทำไม top_ratings_indices ได้ ratings แค่ 0.49xxxxxx

In [22]:
ratings[-10:] #before np.sort(ratings)

array([0.50069773, 0.5056566 , 0.49859408, 0.4937586 , 0.4917437 ,
       0.50574154, 0.4888093 , 0.500226  , 0.4845653 , 0.5057441 ],
      dtype=float32)

In [35]:
ratings[-10:] #after np.sort(ratings)

array([0.51912624, 0.519493  , 0.5196274 , 0.52013177, 0.5208804 ,
       0.5210248 , 0.521421  , 0.5214978 , 0.52181786, 0.52203035],
      dtype=float32)

In [ ]:
เดี๋ยวยังไงต้องหมุน object ratings นี่เล่นอยู่แล้ว เพื่อจะเอา dataframe.to_dict() ใส่กลับไปให้ flask

In [25]:
ratings.sort_values(ascending=False)

AttributeError: 'numpy.ndarray' object has no attribute 'sort_values'

In [31]:
np.sort(ratings)

array([0.45431435, 0.45590764, 0.45590773, ..., 0.5214978 , 0.52181786,
       0.52203035], dtype=float32)

In [33]:
ratings[-10:]

array([0.51912624, 0.519493  , 0.5196274 , 0.52013177, 0.5208804 ,
       0.5210248 , 0.521421  , 0.5214978 , 0.52181786, 0.52203035],
      dtype=float32)

In [43]:
ratings.argsort()[-20:-1]

array([9719, 9720, 9721, 9722, 9723, 9724, 9725, 9726, 9727, 9728, 9729,
       9730, 9731, 9732, 9733, 9734, 9735, 9736, 9737])

In [44]:
ratings.argsort()[-20:]

array([9719, 9720, 9721, 9722, 9723, 9724, 9725, 9726, 9727, 9728, 9729,
       9730, 9731, 9732, 9733, 9734, 9735, 9736, 9737, 9738])

In [ ]:
ตอนรายงานผลกลับไปที่ flask อยากให้โชว์
index
title
ratings

In [6]:
movies_not_watched

index  movieId                                      title  \
0         0        1                           Toy Story (1995)   
1         1        2                             Jumanji (1995)   
2         2        3                    Grumpier Old Men (1995)   
3         3        4                   Waiting to Exhale (1995)   
4         4        5         Father of the Bride Part II (1995)   
...     ...      ...                                        ...   
9737   9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   9738   193583               No Game No Life: Zero (2017)   
9739   9739   193585                               Flint (2017)   
9740   9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  fake_id  
0     Adventure|Animation|Children|Comedy|Fantasy        1  
1                      Adventure|Children|Fantasy        1  
2                                  Comedy|Romance        1  
3                            Comedy|Drama|Romance        1  
4                                          Comedy        1  
...                                           ...      ...  
9737              Action|Animation|Comedy|Fantasy        1  
9738                     Animation|Comedy|Fantasy        1  
9739                                        Drama        1  
9740                             Action|Animation        1  
9741                                       Comedy        1  

[9739 rows x 5 columns]

In [ ]:
import numpy as np

movie_id_unique = 'SELECT * FROM movies'
all_movies = pd.read_sql(movie_id_unique, engine)

#remove the input movies from all_movies
movies_not_watched = all_movies[~all_movies['movieId'].isin(watched_movie_id_list)]
movies_not_watched.loc[:,'fake_id'] = np.ones(len(movies_not_watched), dtype =int)

#get all_ratings from sqlite
query = 'SELECT "userId", ratings."movieId", movies.title, rating FROM ratings JOIN movies ON ratings."movieId" = movies."movieId";'
all_ratings = pd.read_sql(query, engine)

#remove the watched movies from all_ratings
not_all_ratings = all_ratings[~all_ratings['movieId'].isin(watched_movie_id_list)]

#remove movieId and ratings of the watched movies???
movieindex = not_all_ratings['movieId'].unique().tolist()
dl_movie2movie_encoded = {x: i for i, x in enumerate(movieindex)}
dl_movie_encoded2movie = {i: x for i, x in enumerate(movieindex)}

not_all_ratings.loc[:,"movie"] = not_all_ratings["movieId"].map(dl_movie2movie_encoded)
not_all_ratings.loc[:,"rating"] = not_all_ratings["rating"].values.astype(np.float32)

#map userId from ?? to not_all_ratings ?? what do i do with the users??

not_all_user_ids = not_all_ratings["userId"].unique().tolist()
dl_user2user_encoded = {x: i for i, x in enumerate(not_all_user_ids)}
dl_userencoded2user = {i: x for i, x in enumerate(not_all_user_ids)}

not_all_ratings.loc[:,"user"] = not_all_ratings["userId"].map(dl_user2user_encoded)

min_rating = min(not_all_ratings["rating"])
max_rating = max(not_all_ratings["rating"])
num_users = len(dl_user2user_encoded)
num_movies = len(dl_movie_encoded2movie)
print(
        "Number of users: {}, Number of Movies: {}, Min rating: {}, Max rating: {}".format(
            num_users, num_movies, min_rating, max_rating
        )
    )

#define training data
df = not_all_ratings.sample(frac=1, random_state=42)
x = not_all_ratings[["user", "movie"]].values

    # Normalize the targets between 0 and 1. Makes it easy to train.
y = not_all_ratings["rating"].apply(lambda x: (x - min_rating) / (max_rating - min_rating)).values
    # Assuming training on 90% of the data and validating on 10%.
train_indices = int(0.9 * df.shape[0])
x_train, x_val, y_train, y_val = (
        x[:train_indices],
        x[train_indices:],
        y[:train_indices],
        y[train_indices:],
    )

#inference
user_movie_array = movies_not_watched[['fake_id','index']]
max_movie_index = user_movie_array['index'].max()
that = user_movie_array.to_numpy()

EMBEDDING_SIZE = 50

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

class RecommenderNet(keras.Model):
        def __init__(self, num_users, num_movies, embedding_size, **kwargs):
            super(RecommenderNet, self).__init__(**kwargs)
            self.num_users = num_users
            self.num_movies = num_movies
            self.embedding_size = embedding_size
            self.user_embedding = layers.Embedding(
                num_users,
                embedding_size,
                embeddings_initializer="he_normal",
                embeddings_regularizer=keras.regularizers.l2(1e-6),
            )
            self.user_bias = layers.Embedding(num_users, 1)
            self.movie_embedding = layers.Embedding(
            #change this line from num_movies to max_movie_index+1
                max_movie_index+1,
                embedding_size,
                embeddings_initializer="he_normal",
                embeddings_regularizer=keras.regularizers.l2(1e-6),
            )
            #and this line (input_dim)
            self.movie_bias = layers.Embedding(max_movie_index+1, 1)

        def call(self, inputs):
            user_vector = self.user_embedding(inputs[:, 0])
            user_bias = self.user_bias(inputs[:, 0])
            movie_vector = self.movie_embedding(inputs[:, 1])
            movie_bias = self.movie_bias(inputs[:, 1])
            dot_user_movie = tf.tensordot(user_vector, movie_vector, 2)
            # Add all the components (including bias)
            x = dot_user_movie + user_bias + movie_bias
            # The sigmoid activation forces the rating to between 0 and 1
            return tf.nn.sigmoid(x)


model = RecommenderNet(num_users, num_movies, EMBEDDING_SIZE)
model.compile(
        loss=tf.keras.losses.BinaryCrossentropy(), optimizer=keras.optimizers.Adam(lr=0.001)
    )
ratings = model.predict(that).flatten()

top_ratings_indices = ratings.argsort()[-10:][::-1]
movies_not_watched.loc[movies_not_watched['index'].isin(top_ratings_indices)]

In [1]:
movies_not_watched.loc[movies_not_watched['index'].isin(top_ratings_indices)]

NameError: name 'movies_not_watched' is not defined

In [2]:
pwd

'/flask_jupyter'

In [ ]:
อะ คือตรงนี้ ลิสท์ที่กลับมาจาก user input มันให้เลือกด้วยลิสท์ all_movies เพราะจะให้ไปเลือกจาก all_ratings ก็คงประหลาด
ถึงแม้ว่า movieId ใน all_ratings ก็มีเหมือนกัน แต่มันไม่ต่อกัน คือเลขอินเด็กซ์มันไม่สะท้อนถึง unique list
ที่มีจำนวนหนังทั้งหมด 9742 เรื่อง

มันเป็นการสร้างความสัมพันธ์ จะนึกเป็นก้อนคิวบ์สามมิติสองก้อน แล้วมีเส้นๆเชื่อมกันเป็นเน็ตเวิร์คก็ได้
แล้วแต่ละจุด ก็พล็อตด้วยเลขเว็คเตอร์ ซึ่งก็คือ embedding นั่นเอง
แล้วเส้นความสัมพันธ์ก็คือ weight
ว่าได้เท่าไหร่ ห่างจาก 0.5 มากน้อยแค่ไหน

เอา 10 อันดับที่ใกล้กับ 0.5 มากสุด
คือก็คือ ย้อนไปห้า เดินหน้าไปห้า ก็ได้เป็น
0.495 ถึง 0.505

ทำไมต้องเป็น 0.5
ก็คือระยะห่างระหว่าง 2 จุด
คือจุดว่า user คนนี้ให้ rating หนังเรื่องนี้เท่านี้ เต็ม 5.0
แล้ว user ของเราคนนี้จะให้เท่าไหร่

ยังไงก็ต้องมี user embedding ด้วย
เพราะมัน predict against person/identity

In [ ]:
เสร็จก็เลยไปเพิ่มคอลัมน์ not_all_ratings['index'] เพื่อจะได้เรียกหนังเรื่องนึงได้ ตาม index ของมัน
แล้วก็ใส่ not_all_ratings['user'] ด้วย
แต่มันมีอยู่แล้วนี่หว่า??
แต่มันเริ่มต้นที่ 0-609 เลยต้องไป encode รอบนึงก่อน? ไรเงี้ยเหรอ?

เสร็จก็เอา 

In [10]:
not_all_ratings[80000:80020]

userId  movieId                                            title  \
80294     506    41571                       Memoirs of a Geisha (2005)   
80295     506    45447                        Da Vinci Code, The (2006)   
80296     506    45720                    Devil Wears Prada, The (2006)   
80297     506    45880                          Marie Antoinette (2006)   
80298     506    47629                                 The Queen (2006)   
80299     506    48997          Perfume: The Story of a Murderer (2006)   
80300     506    49286                              Holiday, The (2006)   
80301     506    51834                             Becoming Jane (2007)   
80302     506    52973                                Knocked Up (2007)   
80303     506    52975                                 Hairspray (2007)   
80304     506    53000                            28 Weeks Later (2007)   
80305     506    53125  Pirates of the Caribbean: At World's End (2007)   
80306     506    53894                                     Sicko (2007)   
80307     506    54259                                  Stardust (2007)   
80308     506    54272                       Simpsons Movie, The (2007)   
80309     506    55052                                 Atonement (2007)   
80310     506    56367                                      Juno (2007)   
80311     506    56782                       There Will Be Blood (2007)   
80312     506    56949                                27 Dresses (2008)   
80313     506    58154                    Other Boleyn Girl, The (2008)   

       rating  
80294     3.0  
80295     0.5  
80296     3.0  
80297     3.0  
80298     4.0  
80299     3.5  
80300     1.0  
80301     3.0  
80302     3.5  
80303     3.0  
80304     4.0  
80305     0.5  
80306     3.5  
80307     3.0  
80308     2.0  
80309     3.0  
80310     4.0  
80311     4.0  
80312     3.0  
80313     3.0

In [14]:
not_all_ratings['movieId'] ไม่ซ้ำกันเลยซักกะบรรทัดหรือเปล่า ถึงแม้ว่าจะเป็นหนังเรื่องเดียวกัน
ไม่หนิ
สำหรับหนังเรื่อง the Davinci Code ทุกบรรทัดเป็น 45447

KeyError: "None of [Index(['Toy Story (1995)', 'Grumpier Old Men (1995)', 'Heat (1995)',\n       'Seven (a.k.a. Se7en) (1995)', 'Usual Suspects, The (1995)',\n       'From Dusk Till Dawn (1996)', 'Bottle Rocket (1996)',\n       'Braveheart (1995)', 'Rob Roy (1995)', 'Canadian Bacon (1995)',\n       ...\n       'The Magnificent Seven (2016)', 'Blair Witch (2016)', '31 (2016)',\n       'Arrival (2016)', 'Rogue One: A Star Wars Story (2016)', 'Split (2017)',\n       'John Wick: Chapter Two (2017)', 'Get Out (2017)', 'Logan (2017)',\n       'The Fate of the Furious (2017)'],\n      dtype='object', length=100474)] are in the [index]"

In [15]:
not_all_ratings.loc[not_all_ratings['movieId'] == 45447]

userId  movieId                      title  rating
3434       21    45447  Da Vinci Code, The (2006)     3.5
7828       52    45447  Da Vinci Code, The (2006)     3.5
8932       62    45447  Da Vinci Code, The (2006)     3.5
9943       64    45447  Da Vinci Code, The (2006)     2.5
16592     105    45447  Da Vinci Code, The (2006)     4.0
17536     111    45447  Da Vinci Code, The (2006)     4.0
25535     177    45447  Da Vinci Code, The (2006)     3.5
30362     212    45447  Da Vinci Code, The (2006)     3.5
31976     219    45447  Da Vinci Code, The (2006)     2.5
32760     222    45447  Da Vinci Code, The (2006)     3.0
33519     226    45447  Da Vinci Code, The (2006)     4.0
33863     230    45447  Da Vinci Code, The (2006)     3.5
34502     232    45447  Da Vinci Code, The (2006)     3.5
35545     239    45447  Da Vinci Code, The (2006)     3.5
36106     246    45447  Da Vinci Code, The (2006)     3.0
36856     249    45447  Da Vinci Code, The (2006)     3.5
40329     274    45447  Da Vinci Code, The (2006)     3.0
41378     280    45447  Da Vinci Code, The (2006)     4.0
43122     288    45447  Da Vinci Code, The (2006)     3.0
43775     292    45447  Da Vinci Code, The (2006)     4.0
45054     298    45447  Da Vinci Code, The (2006)     0.5
46279     305    45447  Da Vinci Code, The (2006)     3.0
47592     307    45447  Da Vinci Code, The (2006)     2.0
49428     318    45447  Da Vinci Code, The (2006)     3.5
53344     352    45447  Da Vinci Code, The (2006)     3.5
54732     361    45447  Da Vinci Code, The (2006)     4.0
57714     380    45447  Da Vinci Code, The (2006)     3.0
58470     381    45447  Da Vinci Code, The (2006)     3.0
58734     382    45447  Da Vinci Code, The (2006)     3.0
60206     387    45447  Da Vinci Code, The (2006)     3.0
61639     408    45447  Da Vinci Code, The (2006)     3.5
64515     414    45447  Da Vinci Code, The (2006)     3.0
65852     424    45447  Da Vinci Code, The (2006)     3.0
66991     432    45447  Da Vinci Code, The (2006)     4.0
68204     438    45447  Da Vinci Code, The (2006)     3.0
69696     448    45447  Da Vinci Code, The (2006)     2.0
72346     466    45447  Da Vinci Code, The (2006)     4.0
75931     477    45447  Da Vinci Code, The (2006)     4.0
77020     480    45447  Da Vinci Code, The (2006)     3.5
77762     483    45447  Da Vinci Code, The (2006)     3.0
79019     489    45447  Da Vinci Code, The (2006)     3.5
80295     506    45447  Da Vinci Code, The (2006)     0.5
80642     509    45447  Da Vinci Code, The (2006)     3.0
81821     517    45447  Da Vinci Code, The (2006)     0.5
84520     542    45447  Da Vinci Code, The (2006)     3.5
86409     560    45447  Da Vinci Code, The (2006)     3.0
89731     580    45447  Da Vinci Code, The (2006)     4.0
91174     590    45447  Da Vinci Code, The (2006)     2.5
98402     606    45447  Da Vinci Code, The (2006)     2.5

In [10]:
user_movie_ratings = pd.pivot_table(all_ratings, values='rating', index='userId', columns='movieId')
user_movie_ratings

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     NaN     4.0     NaN     NaN     4.0     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...     ...     ...     ...     ...     ...     ...   
606         2.5     NaN     NaN     NaN     NaN     NaN     2.5     NaN   
607         4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
608         2.5     2.0     2.0     NaN     NaN     NaN     NaN     NaN   
609         3.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
610         5.0     NaN     NaN     NaN     NaN     5.0     NaN     NaN   

movieId  9       10      ...  193565  193567  193571  193573  193579  193581  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
606         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
607         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
608         NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
609         NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
610         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  193583  193585  193587  193609  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  
...         ...     ...     ...     ...  
606         NaN     NaN     NaN     NaN  
607         NaN     NaN     NaN     NaN  
608         NaN     NaN     NaN     NaN  
609         NaN     NaN     NaN     NaN  
610         NaN     NaN     NaN     NaN  

[610 rows x 9724 columns]

In [11]:
user_movie_id_ratings_matrix = user_movie_ratings.fillna(0)
user_movie_id_ratings_matrix

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     0.0     4.0     0.0     0.0     4.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...         ...     ...     ...     ...     ...     ...     ...     ...   
606         2.5     0.0     0.0     0.0     0.0     0.0     2.5     0.0   
607         4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
608         2.5     2.0     2.0     0.0     0.0     0.0     0.0     0.0   
609         3.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
610         5.0     0.0     0.0     0.0     0.0     5.0     0.0     0.0   

movieId  9       10      ...  193565  193567  193571  193573  193579  193581  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
606         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
607         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
608         0.0     4.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
609         0.0     4.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
610         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  193583  193585  193587  193609  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  
...         ...     ...     ...     ...  
606         0.0     0.0     0.0     0.0  
607         0.0     0.0     0.0     0.0  
608         0.0     0.0     0.0     0.0  
609         0.0     0.0     0.0     0.0  
610         0.0     0.0     0.0     0.0  

[610 rows x 9724 columns]

In [12]:
number_of_genres = 10
m = NMF(n_components=number_of_genres)
m.fit(user_movie_id_ratings_matrix)

NMF(n_components=10)